version: '3'
services:
  electron:
    image: "cyp-dock-cucum-report"
    command: "cy:run-with-report"
    volumes:
      - ./cypress:/cypress
      - ./cypress.json:/cypress.json
      - ./report.js:/report.js
      - ./package.json:/package.json
      - ./cucumber_report/electron:/cucumber_report
  chrome:
    image: "cyp-dock-cucum-report"
    command: "cy:run:chrome-with-report"
    volumes:
      - ./cypress:/cypress
      - ./cypress.json:/cypress.json
      - ./report.js:/report.js
      - ./package.json:/package.json
      - ./cucumber_report/chrome:/cucumber_report
  firefox:
    image: cyp-dock-cucum-report
    command: "cy:run:firefox-with-report"
    environment:
      - DEBUG=cypress:server:browsers:firefox-util,cypress:server:util:process_profiler
    volumes:
      - ./cypress:/cypress
      - ./cypress.json:/cypress.json
      - ./report.js:/report.js
      - ./package.json:/package.json
      - ./cucumber_report/firefox:/cucumber_report
